### ISSUE TITLE
The "correct" way to load a float to an AI record

### ISSUE THREAD

**Issue by nariox** [mdavidsaver/pyDevSup#34]
Hello all,

I have been working on a new device support IOC (basically a wrapper to libindi). One of the situations I have encountered is that libindi returns to me a floating point number and then I need to set the value of my record. I am somewhat new to EPICS, so maybe I am missing something, but it seems that the value for an AI record can only be derived by as `VAL = ASLO*RVAL + AOFF` (ignoring for now further conversions like `SMOO`, `ESLO`, `EGUL`, etc). Is there a way to directly write to VAL? If not, what would the canonical way to approach this?

For now, I am hard-coding the number of decimal spaces to 1e-6 (_i.e.,_ `ASLO` = 1e-6) and then setting `RVAL` accordingly (_i.e.,_ `RVAL  = new_val/ASLO`), but I have a feeling this is not the best way to go about it. I _could_ do `ASLO = 10**-len(str(new_val).split('.')[1]`, but that feels like I am overengineering it (nevertheless, would there be a way to set ASLO and RVAL in an atomic way).

**Comment by mdavidsaver** [comment]
> ... Is there a way to directly write to VAL?  ...

Yes.  You are not the first wanting to do this, and certainly not the first to miss the magic `return 2` (with the C API) to bypass the `RVAL- > VAL` logic.  With pyDevSup this is triggered by adding at attribute `raw=True`.

http://mdavidsaver.github.io/pyDevSup/interfaces.html?highlight=raw#DeviceSupport.raw

one example:

https://github.com/mdavidsaver/pyDevSup/blob/39df25cb83269de5e77a2b50c7adc66dc175e693/weatherApp/weather.py#L44-L46

**Comment by nariox** [comment]
Ouch, it was right there in the documentation! Sorry about that and thank you for the prompt help.
