### ISSUE TITLE
[QUESTION] (Compatibility) Using EPICS v7 & PVAccess

### ISSUE THREAD

**Issue by crispd** [mdavidsaver/pyDevSup#38]
Hello there! I've gotten a lot of mileage out of pydevsup for years (FRIB), but we had EPICS v3 & used CA. Does pydevsup work with EPICS v7 & PVA?

**Comment by mdavidsaver** [comment]
In short.  Yes.  Transparently.

pyDevSup interacts with the EPICS process database.  aka. records.  In the PVA world, the QSRV module exposes records to PVA clients.

**Comment by crispd** [comment]
Ok, great! I figured as much, but wanted to make sure I wasn't missing some detail. Thank you sir!
