### ISSUE TITLE
TableBase doesn't work for more than one level inheritance

### ISSUE THREAD

**Issue by brunoseivam** [mdavidsaver/pyDevSup#4]
Currently `TableBase` iterates over its attributes as follows:

https://github.com/mdavidsaver/pyDevSup/blob/ab867e3bee5433556ed3b1fe723249393fc5cb42/devsupApp/src/devsup/ptable.py#L301-L301

For the following case the `Child` class will only have the `child_param` parameter in its `_parameters`.

``` python
class Parent(PT.TableBase):
    parent_param = PT.Parameter()

class Child(Parent):
    child_param = PT.Parameter()
```

Maybe something like this should be used for the iteration instead?

``` python
for k, v in [(k, getattr(self, k) for k in dir(self)]:
```

**Comment by mdavidsaver** [comment]
I should have used inspect.getmembers()

https://docs.python.org/2.7/library/inspect.html#inspect.getmembers

**Comment by mdavidsaver** [comment]
Changed with d6685b49b94af756791c0ea0e87912d64100efbb.  Can you confirm that this has the intended effect?

**Comment by mdavidsaver** [comment]
Also note that I've engaged in some modernization, so EPICS_BASE no longer has a default and should be set in configure/RELEASE.local
