### ISSUE TITLE
SIGINT is being swallowed by the Python interpreter

### ISSUE THREAD

**Issue by brunoseivam** [mdavidsaver/pyDevSup#5]
When running an IOC with pyDevSup `SIGINT` is being ignored. A workaround that I used is to have the following snippet in the startup script:

```bash
py "import signal"
py "signal.signal(signal.SIGINT, signal.SIG_DFL)"
```

Maybe this should be present in pyDevSup's initialization code?

**Comment by mdavidsaver** [comment]
Your right.  I'm not sure where the culprit(s) are though.  Probably a bad combination of python and readline, which both install their hooks.  Although it also seems that the glibc version of system() is also changing handler for SIGINT and SIGQUIT.

FYI, you can break with Ctrl+d (EOF) if you're just looking for a quick way to exit cleanly.

**Comment by brunoseivam** [comment]
Looks like using [`Py_InitializeEx(0)`](https://docs.python.org/2/c-api/init.html#c.Py_InitializeEx) instead of `Py_Initialize()` should do the trick. However, it looks like [this is being ignored](https://bugs.python.org/issue35233) in CPython <3.7...

**Comment by mdavidsaver** [comment]
Hey, how about that.  Looks like a simple enough change, and at least it will be correct going forward.

Could I ask you to make/test this change on top of #12?  There `Py_Initialize()` has moved to `pyIocApp/setup.c`.

**Comment by brunoseivam** [comment]
I tried pyDevSup at devel tip, using Python 3.6, with no modifications. Here's the output of running my IOC with this new pyDevSup:

```
$ ./st.cmd 
#!../../bin/linux-x86_64/tst
< envPaths
epicsEnvSet("IOC","ioc-tst")
epicsEnvSet("TOP","/home/martins/tmp")
epicsEnvSet("PYDEVSUP","/home/martins/workspace/pyDevSup")
epicsEnvSet("EPICS_BASE","/usr/lib/epics")
epicsEnvSet("PYEPICS_LIBCA", "/usr/lib/epics/lib/linux-x86_64/libca.so")
#epicsEnvSet("DIAGSTD_DISABLE", "YES")
epicsEnvSet("PREFIX", "tst:")
dbLoadDatabase("/home/martins/tmp/dbd/tst.dbd",0,0)
tst_registerRecordDeviceDriver(pdbbase)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'devsup'
py "import tst"
st.cmd line 12: Command py not found.
py "tst.build()"
st.cmd line 13: Command py not found.
dbLoadRecords("/home/martins/tmp/db/tst.db", "P=tst:")
Can't set "tst:TRIGGER_CMD.DTYP" to "Python Device"
Error at or before ")" in file "/home/martins/tmp/db/tst.db" line 2
Can't set "tst:A_CSET.DTYP" to "Python Device"
ErrorCan't set "tst:B_CSET.DTYP" to "Python Device"
ErrorCan't set "tst:SUM_RD.DTYP" to "Python Device"
ErroriocInit()
Starting iocInit
############################################################################
## EPICS R3.15.6-1+frib1+0~20190305190007.9+debian09~1.gbp1d596a
## EPICS Base built Mar  5 2019
############################################################################
PV: tst:SUM_RD scanAdd: I/O Intr not valid (no get_ioint_info)

iocRun: All initialization complete
epics> ^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
KeyboardInterrupt
```

I put the test IOC code in this gist: https://gist.github.com/brunoseivam/206d138d7fe96648482dcb8f8acee927

I'll investigate further

**Comment by brunoseivam** [comment]
Ok, I think I know what the issue is. The generated stuff in pyDevSup moved from `python3.6/` to `python3.6m/` on my system. However, `PYDIR` is `"python3.6"` here: 
https://github.com/mdavidsaver/pyDevSup/blob/93a4d05866a151b1192fd359e94013b9530391e3/pyIocApp/setup.c#L53

Changing this line:
https://github.com/mdavidsaver/pyDevSup/blob/93a4d05866a151b1192fd359e94013b9530391e3/pyIocApp/Makefile#L28

To `setup_CPPFLAGS += -DPYDIR=\"python$(PY_LD_VER)\"` solves the issue.


Then a new error is emmited by the IOC: `AttributeError: 'dict' object has no attribute 'iteritems'`, which I think is fixed on master.

**Comment by brunoseivam** [comment]
Back to the original issue, it seems that `Py_InitializeEx(0)` works as expected: i.e., doesn't work for Python 3.6 but doesn't adversely affect anything. So I'll open a PR for that and stick with the workaround that I have for Python <3.7
